// Generated by scripts/sync-review-policy.mjs. Do not edit by hand.
export const REVIEW_POLICY_VERSION =
  "review-leadership-situations-00b1e69c8dfc2d39";
export const REVIEW_POLICY_SOURCE_HASH =
  "00b1e69c8dfc2d3991698f31908ced6f7d53b172895d27a9b6c03167830d0b9b";
